### ISSUE TITLE
Update for Zeek 3?

### ISSUE THREAD

**Issue by kraigu** [ncsa/bro-doctor#12]
root@idsbox:/usr/local/zeek# zeekctl doctor

Warning: ZeekControl plugin uses legacy BroControl API. Use
'import ZeekControl.plugin' instead of 'import BroControl.plugin'

Doesn't seem to harm operation, at least for now.

**Comment by JustinAzoff** [comment]
Weird.. that  shouldn't happen.  What version of the plugin do you have installed?

I specifically do

```
try:
    import ZeekControl.plugin as PluginBase
    from ZeekControl import cmdresult
    BINARY = "zeek"
except ImportError:
    import BroControl.plugin as PluginBase
    from BroControl import cmdresult
    BINARY = "bro"
```

so it should try the new name first to avoid that warning

**Comment by kraigu** [comment]
# zkg list
zeek/j-gras/add-node-names (installed: master) - Adds cluster node name to logs.
zeek/j-gras/bro-af_packet-plugin (installed: 1.4.0) - This plugin provides native AF_Packet support for Bro.
zeek/ncsa/bro-doctor (installed: 2.0.1) - A broctl plugin that helps you troubleshoot common problems For cluster-related checks, the package "add-node-names" is recommended.

**Comment by kraigu** [comment]
Oh sigh. It's probably one of the OTHER plugins that's causing that.
